//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpOAuth2.Provider.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AuthorizationEndpointResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthorizationEndpointResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpOAuth2.Provider.Globalization.AuthorizationEndpointResources", typeof(AuthorizationEndpointResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current authorization context already contains an authorization token.
        /// </summary>
        public static string AuthorizationContextContainsToken {
            get {
                return ResourceManager.GetString("AuthorizationContextContainsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client &apos;{0}&apos; is invalid, unauthorized, or has invalid credentials.
        /// </summary>
        public static string InvalidClient {
            get {
                return ResourceManager.GetString("InvalidClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; content type is not valid for the request.
        /// </summary>
        public static string InvalidContentType {
            get {
                return ResourceManager.GetString("InvalidContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; redirect uri, is unregistered or invalid..
        /// </summary>
        public static string InvalidRedirectUri {
            get {
                return ResourceManager.GetString("InvalidRedirectUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method is not allowed for this request.
        /// </summary>
        public static string InvalidRequestMethod {
            get {
                return ResourceManager.GetString("InvalidRequestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource owner denied the authorization request.
        /// </summary>
        public static string ResourceOwnerDenied {
            get {
                return ResourceManager.GetString("ResourceOwnerDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource owner who is approving this authorization is not included.
        /// </summary>
        public static string ResourceOwnerNotIncluded {
            get {
                return ResourceManager.GetString("ResourceOwnerNotIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the {0} url into an instance of a Uri.
        /// </summary>
        public static string UriParseFailure {
            get {
                return ResourceManager.GetString("UriParseFailure", resourceCulture);
            }
        }
    }
}
