//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpOAuth2.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TokenEndpointResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TokenEndpointResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpOAuth2.Globalization.TokenEndpointResources", typeof(TokenEndpointResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization code &apos;{0}&apos; is invalid or expired.
        /// </summary>
        public static string InvalidAuthorizationGrant {
            get {
                return ResourceManager.GetString("InvalidAuthorizationGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization code was not issued to this client.
        /// </summary>
        public static string InvalidAuthorizationGrantForClient {
            get {
                return ResourceManager.GetString("InvalidAuthorizationGrantForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client &apos;{0}&apos; authentication failed.
        /// </summary>
        public static string InvalidClientCredentials {
            get {
                return ResourceManager.GetString("InvalidClientCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grant &apos;{0}&apos; for this request unauthorzed, invalid, expired or revoked.
        /// </summary>
        public static string InvalidGrant {
            get {
                return ResourceManager.GetString("InvalidGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All token requests must be made through HTTP POST verb.
        /// </summary>
        public static string InvalidHttpMethodTokenRequest {
            get {
                return ResourceManager.GetString("InvalidHttpMethodTokenRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client was not included in the token response.
        /// </summary>
        public static string MissingClientInContext {
            get {
                return ResourceManager.GetString("MissingClientInContext", resourceCulture);
            }
        }
    }
}
